name: CI/CD for FastAPI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'  # Trigger the workflow on tag creation (e.g., v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    # Checkout code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Build and push the Docker image to GHCR
    - name: Build and push Docker image to GHCR
      run: |
        docker build -t ghcr.io/lukehouge/fastapi-app:${GITHUB_SHA} .
        docker push ghcr.io/lukehouge/fastapi-app:${GITHUB_SHA}
    
  release:
    name: Release
    runs-on: ubuntu-22.04
    steps:
      - name: Get last tag and create a new version
        id: new_tag
        run: |
          # Get the latest tag from the repository
          last_tag=$(git describe --tags --abbrev=0)
          
          # If there are no tags, start at v0.1.0
          if [[ -z "$last_tag" ]]; then
            new_version="v0.1.0"
          else
            # Increment the version (assuming semantic versioning)
            new_version=$(echo "$last_tag" | awk -F. -v OFS=. '{$NF++; print}')
          fi
          
          # Save the new version as an environment variable
          echo "NEW_VERSION=${new_version}" >> $GITHUB_ENV
  
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.NEW_VERSION }}  # New version tag
        run: |
          # Create a new release with the incremented version as the tag
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="Release $tag" \
              --generate-notes
