name: CI/CD for FastAPI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'  # Trigger the workflow on tag creation (e.g., v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    # Checkout code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Build and push the Docker image to GHCR
    - name: Build and push Docker image to GHCR
      run: |
        docker build -t ghcr.io/lukehouge/fastapi-app:${GITHUB_SHA} .
        docker push ghcr.io/lukehouge/fastapi-app:${GITHUB_SHA}
    
  release:
    name: Release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Get last tag and create a new version
        id: new_tag
        run: |
          # Ensure we are in a git repository
          git fetch --tags  # Fetch all tags to ensure they're available locally
  
          # Try to get the latest tag from the repository, default to v0.1.0 if none exists
          last_tag=$(git describe --tags --abbrev=0 || echo "v0.1.0")
  
          # Start with the new version
          new_version="$last_tag"
  
          # If there are no tags, start at v0.1.0
          if [[ "$last_tag" == "v0.1.0" ]]; then
            new_version="v0.1.0"
          else
            # Increment the version (assuming semantic versioning)
            new_version=$(echo "$last_tag" | awk -F. -v OFS=. '{$NF++; print}')
          fi
  
          # Ensure the new tag doesn't already exist
          tag_exists=$(git tag -l "$new_version")
          
          # Loop to find an unused tag by incrementing the version until it is unique
          while [[ -n "$tag_exists" ]]; do
            new_version=$(echo "$new_version" | awk -F. -v OFS=. '{$NF++; print}')
            tag_exists=$(git tag -l "$new_version")
          done
  
          # Save the new version as an environment variable
          echo "NEW_VERSION=${new_version}" >> $GITHUB_ENV
  
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.NEW_VERSION }}  # New version tag
        run: |
          # Create a new release with the incremented version as the tag
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="Release $tag" \
              --generate-notes
